
%% GYIModel
%{
figure;
subplot(2,2,1);
hold on;
hRes = plot([0:20],(GImpulse.G(2:22)/GImpulse.G(1)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Government Spending');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
ylim([0 1.1]);
hold off;

subplot(2,2,2);
hold on;
hRes = plot([0:20],((GImpulse.Kp(3:23)-GImpulse.Kp(2:22)*(1-Params.Delta))/(GImpulse.Kp(1)*Params.Delta)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Total Investment');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.4 0.4]);
hold off;

subplot(2,2,3);
hRes = plot([0:20],(GImpulse.EntrePopShare(2:22)/GImpulse.EntrePopShare(1)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Entrepreneur Population');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.02 0.04]);
hold off;

subplot(2,2,4);
hold on;
hRes = plot([0:20],((GImpulse.Kd(2:22)-GImpulse.Kd(1:21)*(1-Params.Delta))/(GImpulse.Kd(1)*Params.Delta)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Entrepreneur Investment');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;
print -dpng graph/GIModel.png
%}

%% GYIData
%{
figure;
subplot(2,2,1);
hold on;
hRes = plot([0:20],(GImpulse.G(2:22)/GImpulse.G(1)-1)/0.1);
plot(gov,'r--','LineWidth',2);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Government Spending');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
ylim([0 1.1]);
hold off;

subplot(2,2,2);
hold on;
hRes = plot([0:20],((GImpulse.Kp(3:23)-GImpulse.Kp(2:22)*(1-Params.Delta))/(GImpulse.Kp(1)*Params.Delta)-1)/0.1);
plot(inv,'r--','LineWidth',2);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Total Investment');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.4 0.4]);
hold off;

subplot(2,2,3);
hold on;
hRes = plot([0:20],(GImpulse.EntrePopShare(2:22)/GImpulse.EntrePopShare(1)-1)/0.1);
plot(form/10,'r--','LineWidth',2);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Entrepreneur Population');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.02 0.04]);
hold off;

subplot(2,2,4);
hold on;
hRes = plot([0:20],((GImpulse.Kd(2:22)-GImpulse.Kd(1:21)*(1-Params.Delta))/(GImpulse.Kd(1)*Params.Delta)-1)/0.1);
plot(ncfi,'r--','LineWidth',2);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Entrepreneur Investment');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;
print -dpng graph/GIModelVsData.png
%}

%% NwrPi
%{
figure;
subplot(2,2,1);
hold on;
hRes = plot([0:20],(GImpulse.Ns(2:22)/GImpulse.Ns(1)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Labor Supply');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;

subplot(2,2,2);
hold on;
hRes = plot([0:20],(GImpulse.w(2:22)/GImpulse.w(1)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Wage');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.4 0.4]);
hold off;

subplot(2,2,3);
hRes = plot([0:20],(GImpulse.r(2:22)/GImpulse.r(1)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Interest Rates');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.02 0.04]);
hold off;

subplot(2,2,4);
hold on;
hRes = plot([0:20],(GImpulse.MeanProfit(2:22)/GImpulse.MeanProfit(1)-1)/0.1);
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Average Entrepreneur Profit');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;
print -dpng graph/NwrPi.png
%}

%% output
%{
figure;
subplot(1,2,1);
hold on;
hRes = plot([0:20],(GImpulse.Y(2:22)-GImpulse.Y(1))/(GImpulse.G(3)-GImpulse.G(2)));
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('$');
hTitle = title('Output');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;

subplot(1,2,2);
hold on;
hRes = plot([0:20],(GImpulse.ZImplied(2:22)/GImpulse.ZImplied(1)-1));
set( hRes, 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Computed z');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.4 0.4]);
hold off;
print -dpng graph/YZModel.png

sysRA = load('sysRA');
figure;
hold on;
plot([0:20],(GImpulse.Y(2:22)-GImpulse.Y(1))/(GImpulse.G(3)-GImpulse.G(2)),'LineWidth',2);
plot([0:20], sysRA.IRF(end,1:21),'r--','LineWidth',2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('$');
hTitle = title('Output');
legend('Benchmark','RA');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;
print -dpng graph/YRAModel.png
%}

%% state dependence, credit shock
%{
figure;
subplot(2,2,1);
hold on;
plot([0:20],(MinusLambdaImpulse.Lambda(1:21)-GImpulse.Lambda(1)), 'LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('');
hTitle = title('\lambda');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
hold off;

subplot(2,2,2);
hold on;
plot([0:20],(MinusLambdaImpulse.Kp(1:21)-MinusLambdaImpulse.Kp(1))/MinusLambdaImpulse.Kp(1)*100, 'b','LineWidth', 2);
plot([0:20],(GMinusLambdaImpulse.Kp(1:21)-GMinusLambdaImpulse.Kp(1))/GMinusLambdaImpulse.Kp(1)*100, '--r','LineWidth', 2);
legend('-\lambda','-\lambda,+G');
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Total Capital');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.4 0.4]);
hold off;

subplot(2,2,3);
hold on;
plot([0:20],(MinusLambdaImpulse.EntrePopShare(1:21)-MinusLambdaImpulse.EntrePopShare(1))/MinusLambdaImpulse.EntrePopShare(1)*100, 'b','LineWidth', 2);
plot([0:20],(GMinusLambdaImpulse.EntrePopShare(1:21)-GMinusLambdaImpulse.EntrePopShare(1))/GMinusLambdaImpulse.EntrePopShare(1)*100, '--r','LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Entrepreneur Population');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.02 0.04]);
hold off;

subplot(2,2,4);
hold on;
plot([0:20],(MinusLambdaImpulse.Y(1:21)-MinusLambdaImpulse.Y(1))/MinusLambdaImpulse.Y(1)*100, 'b','LineWidth', 2);
plot([0:20],(GMinusLambdaImpulse.Y(1:21)-GMinusLambdaImpulse.Y(1))/GMinusLambdaImpulse.Y(1)*100, '--r','LineWidth', 2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Output');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;
print -dpng graph/LambdaModel.png
%}

%% state dependence
figure;
subplot(1,2,1);
hold on;
plot((GImpulse.EntrePopShare-GImpulse.EntrePopShare(1))/GImpulse.EntrePopShare(1)*100,'b','LineWidth',2);
plot((GLambdaImpulse.EntrePopShare-LambdaImpulse.EntrePopShare)/LambdaImpulse.EntrePopShare(1)*100,'r--','LineWidth',2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Entrepreneur Population');
legend('No \lambda shock','Negative \lambda shock');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([0 1.1]);
hold off;

subplot(1,2,2);
hold on;
plot((GImpulse.Y-GImpulse.Y(1))/GImpulse.Y(1)*100,'b','LineWidth',2);
plot((GLambdaImpulse.Y-LambdaImpulse.Y)/LambdaImpulse.Y(1)*100,'r--','LineWidth',2);
hXLabel = xlabel('Quarters');
hYLabel = ylabel('%');
hTitle = title('Output');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 14, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
% ylim([-0.4 0.4]);
hold off;
print -dpng graph/LambdaGDiffModel.png

%% Dist
%{
close all;

figure(1);
DistZetaA = squeeze(sum(GImpulse.DistT{1}.*GImpulse.OccPolicyT{1}));
OccPolicyZetaA = squeeze(mean(GImpulse.OccPolicyT{1}));
OccPolicyZetaA = OccPolicyZetaA(2:end,:);
h = mesh(ZetaMesh(2:end,:),AMesh(2:end,:),DistZetaA(2:end,:));
hXLabel = ylabel('Asset');
xlim([1 4.2]);
ylim([0 450]);
zlim([0 0.007]);
view(gca,[-73 20]);
set(gca, ...
  'Box'         , 'off'     , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'ZColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
set(h,'EdgeColor','black');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel]  , ...
    'FontSize'   , 14          );
colormap(parula);
ch = colorbar;
caxis([0 1]);
set( gca                       , ...
    'FontName'   , 'Helvetica' );
print -dpng graph/dist1.png

for j=1:30
figure(1);
DistZetaA = squeeze(sum(GImpulse.DistT{j}.*GImpulse.OccPolicyT{1}));
OccPolicyZetaA = squeeze(mean(GImpulse.OccPolicyT{j}));
OccPolicyZetaA = OccPolicyZetaA(2:end,:);
h = mesh(ZetaMesh(2:end,:),AMesh(2:end,:),DistZetaA(2:end,:));
set(h,'CDataSource','OccPolicyZetaA','FaceColor','interp','CDataMapping','scaled')
set(h,'FaceAlpha',0.8);
refreshdata;
hXLabel = ylabel('Asset');
xlim([1 4.2]);
ylim([0 450]);
view(gca,[-73 20]);
zlim([0 0.007]);

set(gca, ...
  'Box'         , 'off'     , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'ZColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel]  , ...
    'FontSize'   , 14          );

colormap(parula);
ch = colorbar;
caxis([0 1]);
set( gca                       , ...
    'FontName'   , 'Helvetica' );

filName = ['graph/dist' num2str(j+1)];
print ('-dpng',filName);
end
%}